FROM ubuntu:20.04
FROM python:3.8
RUN pip install pandas==1.5.3
RUN pip install scikit-learn
RUN pip install tqdm
RUN pip install numpy==1.24.1
RUN pip install matplotlib==3.7.3
RUN pip install torch==2.0.1
RUN python src-predict/predict.py