version: "3.1"
services:
  app:
    build: .
    volumes:
      - .:/app
      - C:\Users\admin\Desktop\волга\3\input_data:/mnt/source
      - C:\Users\admin\Desktop\волга\3\result:/mnt/result
